name: 'WakaTime Stat Update Action'
author: Avinal

inputs:
  WAKATIME_API_KEY:
    required: true

  GITHUB_TOKEN:
    required: true
    default: ${{ github.token }}
  
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'sun'
  color: 'yellow'
