name: 'Prelaunch Prep'
author: Avinal
description: 'Launch docker'

inputs:
  GH_TOKEN:
    required: true
    default: ${{ github.token }}

  WAKATIME_API_KEY:
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'info'
  color: 'blue'